/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 동챗 API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 정보
 */
export type AuthResponseDtoUser = { [key: string]: unknown };
