/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

/**
 * 사용자 역할
 */
export type AuthResponseDtoUserRole = typeof AuthResponseDtoUserRole[keyof typeof AuthResponseDtoUserRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthResponseDtoUserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
