/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */
import type { AuthResponseDtoUserRole } from './authResponseDtoUserRole';
import type { AuthResponseDtoUserProfileImage } from './authResponseDtoUserProfileImage';

export interface AuthResponseDtoUser {
  /** 사용자 ID */
  id: number;
  /** 사용자명 */
  username: string;
  /** 사용자 역할 */
  role: AuthResponseDtoUserRole;
  /**
   * 프로필 이미지 URL
   * @nullable
   */
  profileImage: AuthResponseDtoUserProfileImage;
}
