/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 동챗 API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */
import type { AuthResponseDtoUser } from './authResponseDtoUser';

export interface AuthResponseDto {
  /** JWT 액세스 토큰 */
  access_token: string;
  /** 사용자 정보 */
  user: AuthResponseDtoUser;
}
