/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 동챗 API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export type ChatControllerGetMessagesParams = {
/**
 * 페이지 번호
 */
page?: number;
/**
 * 페이지당 항목 수
 */
limit?: number;
};
