/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export interface KakaoLoginDto {
  /** 카카오 provider 고유 ID */
  providerId: string;
  /** 표시 이름 */
  nickname?: string;
  /** username 대체 값 */
  username?: string;
}
