/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * 동챗 API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export interface Message {
  /** 메시지 ID */
  id: number;
  /** 발신자 이름 */
  sender: string;
  /** 메시지 내용 */
  content: string;
  /** 생성 시간 */
  createdAt: string;
}
