/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export interface PushSubscribeDto {
  /** 푸시 서비스 엔드포인트 URL */
  endpoint: string;
  /** P256DH 공개 키 */
  p256dh: string;
  /** 인증 비밀키 */
  auth: string;
}
