/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRoomDto
} from '../../lib/api/models';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 채팅방 생성 (1:1 또는 그룹)
 */
export const chatRoomsControllerCreate = (
    createRoomDto: CreateRoomDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/chat/rooms`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createRoomDto, signal
    },
      options);
    }
  


export const getChatRoomsControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatRoomsControllerCreate>>, TError,{data: CreateRoomDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof chatRoomsControllerCreate>>, TError,{data: CreateRoomDto}, TContext> => {

const mutationKey = ['chatRoomsControllerCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatRoomsControllerCreate>>, {data: CreateRoomDto}> = (props) => {
          const {data} = props ?? {};

          return  chatRoomsControllerCreate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChatRoomsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof chatRoomsControllerCreate>>>
    export type ChatRoomsControllerCreateMutationBody = CreateRoomDto
    export type ChatRoomsControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary 채팅방 생성 (1:1 또는 그룹)
 */
export const useChatRoomsControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatRoomsControllerCreate>>, TError,{data: CreateRoomDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatRoomsControllerCreate>>,
        TError,
        {data: CreateRoomDto},
        TContext
      > => {

      const mutationOptions = getChatRoomsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 내 채팅방 목록
 */
export const chatRoomsControllerList = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/chat/rooms`, method: 'GET', signal
    },
      options);
    }
  



export const getChatRoomsControllerListQueryKey = () => {
    return [
    `/chat/rooms`
    ] as const;
    }

    
export const getChatRoomsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof chatRoomsControllerList>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChatRoomsControllerListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof chatRoomsControllerList>>> = ({ signal }) => chatRoomsControllerList(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChatRoomsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof chatRoomsControllerList>>>
export type ChatRoomsControllerListQueryError = ErrorType<unknown>


export function useChatRoomsControllerList<TData = Awaited<ReturnType<typeof chatRoomsControllerList>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatRoomsControllerList>>,
          TError,
          Awaited<ReturnType<typeof chatRoomsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatRoomsControllerList<TData = Awaited<ReturnType<typeof chatRoomsControllerList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatRoomsControllerList>>,
          TError,
          Awaited<ReturnType<typeof chatRoomsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatRoomsControllerList<TData = Awaited<ReturnType<typeof chatRoomsControllerList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 채팅방 목록
 */

export function useChatRoomsControllerList<TData = Awaited<ReturnType<typeof chatRoomsControllerList>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatRoomsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChatRoomsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




