/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export interface CreateRoomDto {
  /** 방 이름 (그룹일 때 주로 사용) */
  name?: string;
  /** 그룹 여부, 기본 false */
  isGroup?: boolean;
  /** 참여자 username 목록 (현재 사용자 제외해도 서버가 포함시킴) */
  participantUsernames: string[];
}
