/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SendFriendRequestDto {
  /** 친구 요청을 보낼 사용자의 아이디 */
  username: string;
}
