/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PushSubscribeDto
} from '../../lib/api/models';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 푸시 알림 구독
 */
export const pushControllerSubscribe = (
    pushSubscribeDto: PushSubscribeDto,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/push/subscribe`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pushSubscribeDto, signal
    },
      options);
    }
  


export const getPushControllerSubscribeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pushControllerSubscribe>>, TError,{data: PushSubscribeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof pushControllerSubscribe>>, TError,{data: PushSubscribeDto}, TContext> => {

const mutationKey = ['pushControllerSubscribe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pushControllerSubscribe>>, {data: PushSubscribeDto}> = (props) => {
          const {data} = props ?? {};

          return  pushControllerSubscribe(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PushControllerSubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof pushControllerSubscribe>>>
    export type PushControllerSubscribeMutationBody = PushSubscribeDto
    export type PushControllerSubscribeMutationError = ErrorType<unknown>

    /**
 * @summary 푸시 알림 구독
 */
export const usePushControllerSubscribe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pushControllerSubscribe>>, TError,{data: PushSubscribeDto}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pushControllerSubscribe>>,
        TError,
        {data: PushSubscribeDto},
        TContext
      > => {

      const mutationOptions = getPushControllerSubscribeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary 푸시 알림 구독 해제
 */
export const pushControllerUnsubscribe = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/push/unsubscribe`, method: 'DELETE'
    },
      options);
    }
  


export const getPushControllerUnsubscribeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError,void, TContext> => {

const mutationKey = ['pushControllerUnsubscribe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, void> = () => {
          

          return  pushControllerUnsubscribe(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PushControllerUnsubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof pushControllerUnsubscribe>>>
    
    export type PushControllerUnsubscribeMutationError = ErrorType<unknown>

    /**
 * @summary 푸시 알림 구독 해제
 */
export const usePushControllerUnsubscribe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pushControllerUnsubscribe>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pushControllerUnsubscribe>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPushControllerUnsubscribeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    