/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * dongchat API
 * 실시간 채팅 애플리케이션 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatControllerGetMessagesParams,
  Message
} from '../../lib/api/models';

import { customInstance } from '../../lib/api-client';
import type { ErrorType } from '../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 저장된 채팅 메시지를 페이지네이션하여 조회합니다.
 * @summary 메시지 조회
 */
export const chatControllerGetMessages = (
    params?: ChatControllerGetMessagesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Message[]>(
      {url: `/chat`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getChatControllerGetMessagesQueryKey = (params?: ChatControllerGetMessagesParams,) => {
    return [
    `/chat`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getChatControllerGetMessagesQueryOptions = <TData = Awaited<ReturnType<typeof chatControllerGetMessages>>, TError = ErrorType<unknown>>(params?: ChatControllerGetMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChatControllerGetMessagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof chatControllerGetMessages>>> = ({ signal }) => chatControllerGetMessages(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: 60000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChatControllerGetMessagesQueryResult = NonNullable<Awaited<ReturnType<typeof chatControllerGetMessages>>>
export type ChatControllerGetMessagesQueryError = ErrorType<unknown>


export function useChatControllerGetMessages<TData = Awaited<ReturnType<typeof chatControllerGetMessages>>, TError = ErrorType<unknown>>(
 params: undefined |  ChatControllerGetMessagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerGetMessages<TData = Awaited<ReturnType<typeof chatControllerGetMessages>>, TError = ErrorType<unknown>>(
 params?: ChatControllerGetMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChatControllerGetMessages<TData = Awaited<ReturnType<typeof chatControllerGetMessages>>, TError = ErrorType<unknown>>(
 params?: ChatControllerGetMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 메시지 조회
 */

export function useChatControllerGetMessages<TData = Awaited<ReturnType<typeof chatControllerGetMessages>>, TError = ErrorType<unknown>>(
 params?: ChatControllerGetMessagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chatControllerGetMessages>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChatControllerGetMessagesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




